increase clang-tidy coverage
matterfi/opentxs-archive pull request #108
Opened 2022-07-18 16:44 UTC by radexx99

2022-07-19 13:48 UTC, Piotrek321 requested changes

2022-07-19 13:48 UTC, Piotrek321 commented on src/blockchain/node/filteroracle/FilterOracle.cpp
> +    const std::optional<bool> resetfilter) const noexcept -> bool
I would leave it unchanged

2022-07-19 13:48 UTC, Piotrek321 commented on src/blockchain/node/wallet/subchain/NotificationStateData.cpp
> +    if (0u == general.size()) { return; }
I would leave it unchanged

2022-07-19 13:48 UTC, Piotrek321 commented on src/blockchain/node/wallet/subchain/NotificationStateData.cpp
> +    if (0u == general.size()) { return; }
I would leave it unchanged

2022-07-19 14:24 UTC, wiesiekpap approved these changes

2022-07-19 14:24 UTC, wiesiekpap commented on src/blockchain/node/wallet/subchain/NotificationStateData.cpp
> +    if (0u == general.size()) { return; }
A c-language programmer never dies in some people... Or is it ecmascript or something?

2022-07-19 14:24 UTC, wiesiekpap commented on src/blockchain/node/wallet/subchain/NotificationStateData.cpp
> +    if (0u == general.size()) { return; }
If you look long enough, you'll find some dude on youtube fiercely advocating this style as a solution to all your problems :-}

2022-07-19 14:26 UTC, Piotrek321 commented on src/blockchain/node/wallet/subchain/NotificationStateData.cpp
> +    if (0u == general.size()) { return; }
I talked with J about that and he said this is fine for him :D (I mean chaning to .empty())

2022-07-19 20:17 UTC, radexx99 commented on src/blockchain/node/filteroracle/FilterOracle.cpp
> +    const std::optional<bool> resetfilter) const noexcept -> bool
GoodPoint

2022-07-19 20:18 UTC, radexx99 commented on src/blockchain/node/wallet/subchain/NotificationStateData.cpp
> +    if (0u == general.size()) { return; }
Yes i missed

2022-07-20 16:20 UTC, radexx99 commented
New Pull Request 111 have been created to merge this work

2022-07-20 16:20 UTC, closed without merging